### ISSUE TITLE
Better instructions how how to fix concourse after restart

### ISSUE THREAD

**Issue by codeword** [concourse/concourse-docker#20]
The current instructions under:
https://github.com/concourse/concourse-docker#caveats

are severely lacking:
what does

```markdown
At the moment, workers running via Docker will not automatically leave the cluster gracefully on shutdown. This means you'll have to run fly prune-worker to reap them.
```

even mean?

how does issue https://github.com/concourse/concourse/issues/1457 even relate to the restart problem or provide any guidance for how to fix it?

If 'concoruse-docker' is the recommended 'getting started' method for using concourse, but when you restart it, it totally craps out and there are no clear instructions for how to fix it. it makes for a *really crappy* onboarding experience.

**Comment by codeword** [comment]
please elaborate on how `fly prune-worker` fixes the problem:
```bash
jbarnes@mobius.lan:~/workspace/hello-concourse [± jrhb|master → local ↑2 ✓|] $ fly -t local prune-worker
error: the required flag `-w, --worker' was not specified
jbarnes@mobius.lan:~/workspace/hello-concourse [± jrhb|master → local ↑2 ✓|] $ fly -t local workers
name        containers  platform  tags  team  state    version
councourse  0           linux     none  none  running  2.1
jbarnes@mobius.lan:~/workspace/hello-concourse [± jrhb|master → local ↑2 ✓|] $ fly -t local prune-worker -w concourse
error: resource not found
```
I assume the worker I need to prune is the one labeled `concourse`

**Comment by vito** [comment]
This is a pretty unconstructive and somewhat rude GitHub issue.

I can't help you to understand something if you just say "what does that even mean?" without explaining at least some specific part that you're confused by and without providing any context to help us understand where you might be getting stuck. I don't doubt that the docs could be made more clear, but you've got to help us help you instead of just complaining.

Is this the first time you're ever using Concourse? Where did you first look for the documentation? How much had you read prior to this repo's README? Do you know what a worker is? Right now the README assumes knowledge of workers and the `fly` CLI, so maybe that's where you're stuck? Maybe we need to flesh out the docs for worker states?

The README calls out the problem and links to the relevant GitHub issue with more context, showing that we're keeping track of the problem (and allowing you to follow updates, e.g. the last comment which indicates that we have a fix for this ready). It provides a pretty simple resolution which can literally only mean one thing (per the [docs](https://concourse-ci.org/administration.html#fly-prune-worker)). It doesn't sound like you tried to follow the instructions prior to opening this issue.

I've updated the README to be a bit more descriptive. I don't know if it's enough, because there's not enough information in this issue to be sure. I'm going to close this issue anyway, and request that you be a bit more empathetic and collaborative in the future. This is a large project and we're not gonna get everything right all the time. We need people to help in whatever way they can.
